title: Arquitectura Cloud
description: Sitio web, orientado a la arquitectura de Software y Cloud.
show_downloads: false

baseurl: "/blog-arquitectura-nube" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://mc-herrera-90.github.io" # change this to the base hostname & protocol for your site

lang: es

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: lorepirri
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

excerpt_separator: <!--more-->

collections_dir: collections

collections:
  m1:
    output: true
  m2:
    output: true
    permalink: /:collection/:slug/
  m3:
    output: true
    permalink: /:collection/:slug/
header_page_refs: ['Kit Tools', 'Acerca de Nosotros', 'trabajos']
